### ISSUE TITLE
Example fail loading fixtures in Windows

### ISSUE THREAD

**Issue by SinHouse** [uralbash/pyramid_pages#51]
Loading example fixtures fail in Windows because native **cp1252** codification is used instead of UTF-8.

I solved it using **encoding** parameter in open() function.
Change in file line 131:
`class Fixtures(object):

    def __init__(self, session):
        self.session = session

    def add(self, model, fixtures):
        here = os.path.dirname(os.path.realpath(__file__))
        file = open(os.path.join(here, fixtures), encoding='utf-8')
        fixtures = json.loads(file.read())
        for fixture in fixtures:
            self.session.add(model(**fixture))
            self.session.flush()
        transaction.commit()`

**Comment by uralbash** [comment]
@SinHouse Thanks!

**Comment by SinHouse** [comment]
@uralbash you're welcome!
